name: Flutter Test (Self-hosted)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Run Flutter Tests on Self-Hosted
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run Dart Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings > analyze_report.txt || true
        
      - name: Upload Analysis Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-analyze-report
          path: analyze_report.txt


      - name: Run tests
        run: flutter test

